### register user
POST http://localhost:3000/register/user/
Content-Type: application/json

{
  "name": "sudheer",
  "age": 27,
  "location": "vizag",
  "email": "sudheer@gmail.com",
  "phone_number": "9876543210",
  "password": "sudheer@123"
}

### login User
POST http://localhost:3000/login/user/
Content-Type: application/json

{
  "phone_number":"810-374-9840",
  "password":"Josephine@123"
}

### Get list of games
GET http://localhost:3000/games/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE2MjIzNjUzMzh9.rTYpY1alF58BXBXUQ163nC4dPhdG9lLa2dsHts408VU


### Update user info
PUT http://localhost:3000/user/update/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE2MjIzNjUzMzh9.rTYpY1alF58BXBXUQ163nC4dPhdG9lLa2dsHts408VU
Content-Type: application/json

{
  "name": "sudheer",
  "age": 27,
  "location": "visakhapatnam",
  "email": "sudheer@yahoo.com"
}

### User gets his aggregated data for each game
GET http://localhost:3000/user/leaderboard/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE2MjIzNjUzMzh9.rTYpY1alF58BXBXUQ163nC4dPhdG9lLa2dsHts408VU

### user gets aggregated data of other users for a specific game
GET http://localhost:3000/games/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE2MjIzNjUzMzh9.rTYpY1alF58BXBXUQ163nC4dPhdG9lLa2dsHts408VU

### Register admin
POST http://localhost:3000/register/admin/
Content-Type: application/json

{
  "username": "abhinav",
  "email": "abhinav@gmail.com",
  "designation": "DBA",
  "password": "abhinav@123"
}

### login admin
POST http://localhost:3000/login/admin/
Content-Type: application/json

{
  "username": "abhinav",
  "password": "abhinav@123"
}

### Admin post result of the game
POST http://localhost:3000/post/result/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiaGluYXYiLCJpYXQiOjE2MjIzNjI4NjB9.GLDKi3t7YDocCrwOB7UGQ7z1MCzqVlEELexxfPPkTTE
Content-Type: application/json

{
  "u1Id": 2,
  "u2Id": 1,
  "scoreU1": 65,
  "scoreU2": 60,
  "win": true,
  "gameId":2
}
